environment:

platform:
    - x64
    - x86

build_script:
    - cmd: dir C:\Libraries\boost
    - cmd: dir C:\Libraries\boost_1_58_0
    - cmd: dir C:\Libraries\boost_1_59_0
    - cmd: dir C:\Libraries\boost_1_60_0
    - cmd: dir C:\Libraries\boost_1_62_0
    - cmd: dir C:\Libraries\boost_1_63_0
    - cmd: dir C:\Libraries\boost_1_64_0
