environment:
  matrix:
    - dummy: true
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - dummy: false

platform:
    - x64
    - x86

build_script:
    - cmd: if %dummy%==false ( dir C:\Libraries\boost )
    - cmd: if %dummy%==false ( dir C:\Libraries\boost_1_58_0 )
    - cmd: if %dummy%==false ( dir C:\Libraries\boost_1_59_0 )
    - cmd: if %dummy%==false ( dir C:\Libraries\boost_1_60_0 )
    - cmd: if %dummy%==false ( dir C:\Libraries\boost_1_62_0 )
    - cmd: if %dummy%==false ( dir C:\Libraries\boost_1_63_0 )
    - cmd: if %dummy%==true ( dir C:\Libraries\boost_1_64_0 )
